version: "3"
services:
    blog:
        container_name: blog
        image: jekyll/jekyll:latest
        command: jekyll serve --watch --force_polling --verbose
        environment:
            TZ: "Asia/Seoul"
        ports:
            - 4000:4000
        volumes:
            - type: bind
              source: .
              target: /srv/jekyll


